### ISSUE TITLE
如何反向代理

### ISSUE THREAD

**Issue by FoamCold** [super-upup/98tang#13]
![image](https://github.com/super-upup/98tang/assets/139764186/0ee21194-1ae3-402b-ac3d-9fe5893dba34)
我反向代理后用域名访问显示Invalid Host header

**Comment by super-upup** [comment]
ip可以，然後域名不可以嗎。如果這樣的話你需要去學習一下nginx/apach的配置，比較繁瑣我這裡也講不清，簡而言之就是將域名的請求轉發到對應的接口。
