### ISSUE TITLE
作者解释一下源码这部分什么意思吗？

### ISSUE THREAD

**Issue by GHang9** [super-upup/98tang#6]
小白，不是很懂，想请作者解释一下。
![屏幕截图 2023-08-15 111822](https://github.com/super-upup/98tang/assets/94511556/5e835692-f7b2-4211-87b1-bf386fec8e65)

**Comment by super-upup** [comment]
接口源自於http://superupup.top

**Comment by GHang9** [comment]
> 接口源自http://superu

**Comment by GHang9** [comment]
> > 接口源自http://superu

是不是就是相当于，我们登录的账号密码全部同步到你的服务器上？

**Comment by super-upup** [comment]
對，不過有加密，不保存無法簽到，您可以自主選擇是否使用。
