### ISSUE TITLE
大佬 后端能放出来吗

### ISSUE THREAD

**Issue by sinosofti** [super-upup/98tang#8]
这个我看请求到你自己的域名上了

**Comment by super-upup** [comment]
後端暫未開放，後面再看看吧

**Comment by sinosofti** [comment]
但是大佬 能私发我一份不 我真的想用起来啊


***@***.***
 
发件人： super-upup
发送时间： 2023-08-17 10:01
收件人： super-upup/98tang
抄送： fly; Author
主题： Re: [super-upup/98tang] 大佬 后端能放出来吗 (Issue #8)
後端暫未開放，後面再看看吧

**Comment by sinosofti** [comment]
这样账号密码都暴漏出去了也不太敢用呀

**Comment by super-upup** [comment]
無盈利項目，自主選擇是否使用，使用前請設置密保郵箱。

**Comment by sinosofti** [comment]
6
